version: "3.2"

services:
  postgraphql:
    image: postgraphql/postgraphql:latest
    ports:
      - "5000:5000"
    environment:
        PGUSER: graphql
        PGPASSWORD: graphql
        PGHOST: graphql_db
        PGDATABASE: graphql_development
        PGPORT: 5432
    links:
        - graphql_db

  graphql_db:
    build:
      context: .
      dockerfile: graphql_db.txt
    volumes:
      - graphql_data:/var/lib/postgresql/data

volumes:
  graphql_data: {}
